### ISSUE TITLE
Console Error when paired with MC Dungeon Weapons 1.19.2

### ISSUE THREAD

**Issue by gamerpotion** [SilverAndro/RPGStats#120]
Hi,
ive been using your rpgstats mod on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg 
After days of disabling and testing mod conflicts, i have found rpgstats(rpgstats-4.3.18+1.19.1.jar) to be conflicting with mc dungeon weapons (mcdw-5.0.4-1.19.jar) and shows the following console message.  you can replicate by just installing rpg stats and mc wep on 1.19.2 and show console.   could this be fixed?

```10:08:26.597
net.minecraft.class_3551
main
Building optimized datafixer
10:08:28.635
FabricLoader/Mixin
main
Error loading class: org/spongepowered/asm/synthetic/args/Args$3 (java.lang.ClassNotFoundException: org/spongepowered/asm/synthetic/args/Args$3)
10:08:30.371
game
org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 184: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:296)
	at org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:859)
	at org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:828)
	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:782)
	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:752)
	at org.spongepowered.asm.util.Locals.getLocalsAt_0_9_2(Locals.java:696)
	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:338)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:154)
	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:148)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector$Context.<init>(ModifyVariableInjector.java:71)
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.preInject(ModifyVariableInjector.java:159)
	at org.spongepowered.asm.mixin.injection.code.Injector.preInject(Injector.java:258)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.preInject(InjectionInfo.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1371)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_1792.method_7867(class_1792.java:74)
	at net.minecraft.class_2248.method_8389(class_2248.java:554)
	at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60)
	at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66)
	at net.minecraft.class_7143.method_41579(class_7143.java:199)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:50)
	at net.minecraft.client.main.Main.method_44604(Main.java:161)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.hasSuperClass(org.spongepowered.asm.mixin.transformer.ClassInfo)" because the return value of "org.spongepowered.asm.mixin.transformer.ClassInfo.forType(org.objectweb.asm.Type, org.spongepowered.asm.mixin.transformer.ClassInfo$TypeLookup)" is null
	at org.spongepowered.asm.util.asm.MixinVerifier.isAssignableFrom(MixinVerifier.java:104)
	at org.objectweb.asm.tree.analysis.SimpleVerifier.isSubTypeOf(SimpleVerifier.java:212)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:400)
	at org.objectweb.asm.tree.analysis.BasicVerifier.naryOperation(BasicVerifier.java:44)
	at org.objectweb.asm.tree.analysis.Frame.executeInvokeInsn(Frame.java:682)
	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:609)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:188)
	... 42 more
  <log4j:Event logger="com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService" timestamp="1664356110371" level="INFO" thread="Render thread">
    <log4j:Message><![CDATA[Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD']]></log4j:Message>
  </log4j:Event>
10:08:30.372
monitor
Process Monitor
XML_ERROR_PARSING`

**Comment by SilverAndro** [comment]
Alright can reproduce

Not sure how easy this would be to fix though, as mixin doesnt give me any useful info

**Comment by SilverAndro** [comment]
This has been tracked down to something with mixin internals trying to resolve some of out mixins that target similar areas

**Comment by gamerpotion** [comment]
> This has been tracked down to something with mixin internals trying to resolve some of out mixins that target similar areas

Hi thats great! just wondering will it be fixed in next update?

**Comment by SilverAndro** [comment]
I dont know if we can even do anything so hard to say

**Comment by SilverAndro** [comment]
Apparently fixed on MCDW side
